### ISSUE TITLE
plot_intermediate_values() got an unexpected keyword argument 'target'

### ISSUE THREAD

**Issue by ricber** [neptune-ai/neptune-optuna#27]
https://github.com/neptune-ai/neptune-optuna/blob/dfa6fd4ca41f0be326cd91f1bead1ddb674f0c99/src/neptune_optuna/impl/__init__.py#L580

Hey, I'm getting an error at this line. The error says `plot_intermediate_values() got an unexpected keyword argument 'target'`. Indeed the Optuna function `plot_intermediate_values() ` has no `target`, nor `target_name` parameters. What's the reason of having them?

https://github.com/optuna/optuna/blob/71ba348b7eb67ba82d1948a067edafb5f858e8f5/optuna/visualization/_intermediate_values.py#L46

**Comment by saneins** [comment]
> https://github.com/neptune-ai/neptune-optuna/blob/dfa6fd4ca41f0be326cd91f1bead1ddb674f0c99/src/neptune_optuna/impl/__init__.py#L580
> 
> Hey, I'm getting an error at this line. The error says `plot_intermediate_values() got an unexpected keyword argument 'target'`. Indeed the Optuna function `plot_intermediate_values() ` has no `target`, nor `target_name` parameters. What's the reason of having them?
> 
> https://github.com/optuna/optuna/blob/71ba348b7eb67ba82d1948a067edafb5f858e8f5/optuna/visualization/_intermediate_values.py#L46

I am also facing the same problem.

**Comment by Blaizzy** [comment]
Hey guys,

Great news! 🎊 

The PR is merged, and the fix will be available on the next release v0.10.2.

**Comment by Blaizzy** [comment]
Hey guys

You can now update to the latest release v0.10.2.

`pip install -U neptune-optuna`

Let me know if anything else pops up :)
