### ISSUE TITLE
Feature Request: Log trial user attributes on neptune

### ISSUE THREAD

**Issue by danielecastellana22** [neptune-ai/neptune-optuna#43]
I want to log on neptune custom trial information, in addition to the one logged automatically.

I think it is enough to log on neptune also the trial user attributes. Actually, I do not understand why user attributes are logged for a study but not for a trial.

Thank you for your help!

**Comment by SiddhantSadangi** [comment]
Hey @danielecastellana22 👋 
Could you explain more about what you mean by _user attributes_?

You can log custom metadata using the base `run`: https://docs.neptune.ai/integrations/optuna/#manually-logging-metadata. 

Would this help?

**Comment by danielecastellana22** [comment]
Thank you for your prompt response! 

I mean the trial user attributes that optuna allows to add during the execution of the objective function:
[https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/003_attributes.html#attributes](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/003_attributes.html#attributes)

It would be great if the function `_log_single_trial` called in `NeptuneCallback` automatically log the user attributes accessible by  `Trial.user_attrs`

I hope this help to clarify.

**Comment by SiddhantSadangi** [comment]
Thanks @danielecastellana22 , this helps!

I'll see if this can be implemented soon ✅

**Comment by SiddhantSadangi** [comment]
Hey @danielecastellana22 ,

I've created PR #44 to add this feature.
Could you test it and let me know if it works for you?

You can install it using `pip install git+https://github.com/neptune-ai/neptune-optuna.git@ss/trial_user_attrs`

**Comment by danielecastellana22** [comment]
Yes, it works! 
I really appreciate your help!

**Comment by SiddhantSadangi** [comment]
Cool, thanks for confirming! 🎉 

We'll merge and release it sometime this week. ✅ 

You can start watching this repository to get notified when the release is out 🔔

**Comment by SiddhantSadangi** [comment]
Hey @danielecastellana22 , thaks again for this feature request!
This has been included in `neptune-optuna` [v1.3.0](https://github.com/neptune-ai/neptune-optuna/releases/tag/1.3.0) 🚀
