### ISSUE TITLE
Feature Request: Consider updating the numpy version dependency

### ISSUE THREAD

**Issue by SebastianEngelhardt** [neptune-ai/neptune-optuna#47]
The current setup requires an old numpy version (smaller 2.0). This causes dependency resolution conflicts with many recent machine learning frameworks. Please consider relaxing this requirement to a broader range of versions.

**Comment by SiddhantSadangi** [comment]
Hey @SebastianEngelhardt 👋 

Thank you for pointing this out. `numpy<2.0` is only supposed to be a `dev` dependency and should not be required by the standard `neptune-optuna` installation.

We will fix the `pyproject.toml` file ✅ 

Meanwhile, you can manually upgrade `numpy` to the latest version, and `neptune-optuna` should work fine. Please let us know if it does not though.

**Comment by SiddhantSadangi** [comment]
Fixed in [neptune-optuna v1.4.1](https://github.com/neptune-ai/neptune-optuna/releases/tag/1.4.1) ✅
